### ISSUE TITLE
Batched packets with sizes over the MTU

### ISSUE THREAD

**Issue by Philanatidae** [GoMint/jRakNet#2]
This is more of a question than an issue (though it _is_ an issue that is in your code). This is referencing the comment In io.gomint.jraknet.Socket.java between lines 36 and 51.

> We allocate buffers able to hold twice the maximum MTU size for the reasons listed below:
> 
> Somehow I noticed receiving datagrams that exceeded their respective connection's MTU by
> far whenever they contained a Batch Packet. As this behaviour comes out of seemingly
> nowhere yet we do need to receive these batch packets we must have room enough to actually
> gather all this data even though it does not seem legit to allocate larger buffers for this
> reason. But as the underlying DatagramSocket provides no way of grabbing the minimum required
> buffer size for the datagram we are forced to play this dirty trick. If - at any point in the
> future - this behaviour changes, please add this buffer size back to its original value:
> MAXIMUM_MTU_SIZE.
> 
> Examples of too large datagrams:
> - Datagram containing BatchPacket for LoginPacket: 1507 bytes the batch packet alone (5th of March 2016)
> 
> Suggestions:
> - Make this value configurable in order to easily adjust this value whenever necessary

First; is this an issue with jRakNet? Or is it coming from MCPE? If I were to use jRakNet on a server and connect it with a client using jRakNet, would I ever have an issue of batch packets being over the MTU? I assume that the issue is on MCPE's side. I am asking this because I am investigating using jRakNet as networking for my game.

Second; I used to develop a server for MCPE. I didn't get far in writing actual server software, but I had studied MCPE's (and RakNet, by accident at the time) protocol. Things have changed since then, of course, but from my understanding RakNet determined the MTU between the client and the server during connection. Might this be the issue? MCPE would determine the max MTU and send as many packets that fit. I might have misinterpreted the documentation at the time, it's been several years.

**Comment by cieldeville** [comment]
Actually I think this is an issue of MCPE and not of (j)RakNet. 

First of all: the MTU is determined by RakNet and not by MCPE and it does so before even establishing a valid connection. RakNet does so by repeatedly sending messages of different lengths to the server until it gets back a response. The server would include the length of the received message which would later become the determined MTU size in said response. This is important for one reason: MCPE has seemingly altered RakNet's behaviour in a variety of ways as other examples of behaviour that differs from the original implementation may be found as well. Thus I suppose this is much more of an MCPE related issue than one of jRakNet.

The bad news is the following, though: Our implementation will have to account for such terrible behaviour of MCPE clients. Thus we do have to allocate such large buffers which takes up quite some amount of memory (currently 64KiB per connection). This number originated from the fact that 16 unsigned bits are used by UDP to specify a datagram's length, thus we need to account for 64KiB at max.

We have actually been thinking of separating jRakNet into two projects before: one that would be standard compliant and one that would contain all necessary adjustments for MCPE. I can unfortunately not make any promises regarding when that might happen yet, though.

If you would like to use jRakNet in your game I, personally, would absolutely fancy that, though I have got to warn you that it's never been battle-tested on a large scale before. Thus, you might have to account for some minor bugs and such, even though we did some extensive unit testing and general field testing already.

I hope I could answer your question thoroughfully. If there's anything else you would like to know feel free to reply.

Best regards,
BlackyPaw.

**Comment by Philanatidae** [comment]
I used MCPE and RakNet interchangeably, probably shouldn't have. I was correct in my thinking, though, that RakNet determines the MTU during connection. I didn't know that MCPE had changed the algorithm, though. Such a pain...

I wonder if other MCPE server software have had the same issue... PocketMine's creator, if I can remember right, wrote a PHP port of RakNet that he uses in PocketMine. That might be something to look into.

This appears to be an issue with MCPE and not jRakNet, so I'll close this issue.
